'use strict';
const test = require('node:test'); const assert = require('node:assert/strict'); const fs = require('node:fs'); const os = require('node:os'); const path = require('node:path');
const { lex } = require('../src/lexer'); const { parse } = require('../src/parser'); const { build } = require('../src/compiler'); const { DarkError } = require('../src/errors');
function project(files) { const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'darktalk-')); for (const [name, source] of Object.entries(files)) fs.writeFileSync(path.join(directory, name), source); return directory; }
async function built(directory, file = 'app.app.talk') { const result = build(path.join(directory, file)); delete require.cache[result.outputFile]; const output = require(result.outputFile); await output.ready; return { result, output }; }
test('lexer recognizes directives, operators and application keywords', () => { const kinds = lex('#add "tools.dark" as tools\nif true { total += 1 }').map((t) => t.type); assert.deepEqual(kinds.slice(0, 9), ['ADD', 'STRING', 'AS', 'IDENTIFIER', 'IF', 'TRUE', 'LBRACE', 'IDENTIFIER', 'PLUSEQ']); });
test('parser creates executable application AST', () => { const program = parse(lex('app Demo\nitems = [1, 2]\nfor item in items { print(item) }')); assert.equal(program.app.name, 'Demo'); assert.equal(program.body[1].type, 'ForStatement'); });
test('recursive .dark modules execute through an entrypoint', async () => { const directory = project({ 'app.app.talk': 'app Demo\n#add "a.dark" as a\nresult = await a.go(5)', 'a.dark': '#add "b.dark" as b\nfunction go(value) { return await b.double(value) }', 'b.dark': 'function double(value) { return value * 2 }' }); const { output } = await built(directory); assert.equal(await output.go?.(1), undefined); assert.ok(fs.existsSync(path.join(directory, 'dist', 'app.js'))); });
test('data, actions, loops and APIs compile into a usable runtime', async () => { const directory = project({ 'app.app.talk': 'app Demo\ndata Item { name: text }\nitem = create Item { name: "one" }\naction names() { values = list Item\nreturn values }\napi items { GET "/items" { return list Item } }' }); const { output } = await built(directory); assert.equal((await output.names()).length, 1); assert.equal(output.dark.api.routes.length, 1); assert.equal((await output.dark.api.routes[0].handler({}))[0].name, 'one'); });
test('Dark Core cannot be shadowed', () => { const directory = project({ 'app.app.talk': 'app Demo\nfunction web() { return 1 }' }); assert.throws(() => build(path.join(directory, 'app.app.talk')), DarkError); });
test('web/AI local-safe runtime and JavaScript imports work without credentials', async () => { const directory = project({ 'app.app.talk': 'app Demo\n#add "helper.js" as helper\nresult = await web.search("dark")\npage = await web.open(result[0].url)\nsummary = await ai.summarize(page.text)\nmessage = await helper.greet("Dark")', 'helper.js': 'exports.greet = async (name) => `Hello ${name}`;' }); const { output } = await built(directory); assert.equal(output.dark.api.routes.length, 0); });
test('events and task declarations compile and events execute', async () => { const directory = project({ 'app.app.talk': 'app Demo\ndata Job { name: text }\nevent job.created(job)\nwhen job.created(job) { copy = job.name }\ntask cleanup every 5 minutes { print("cleanup") }\njob = create Job { name: "report" }\nemit job.created(job)' }); const { output } = await built(directory); assert.equal(output.dark.data.list('Job')[0].name, 'report'); });
